version: "3.9"

services:
  app-rust-to-ftp:
    container_name: app-rust-to-ftp
    build: 
      context: ./app_rust
      dockerfile: ../Dockerfile.Debug
    volumes:
      - ./app_rust:/home/process_files_in_ftp
    depends_on:
      - db-postgres
    networks:
      - app-rust-ftp-network


  db-postgres:
    image: postgres:13
    container_name: app-rust-ftp-postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "savne"
      POSTGRES_DB: "ftp"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - app-rust-ftp-network
    ports:
      - "5432:5432"


#Docker Networks
networks:
  app-rust-ftp-network:
    driver: bridge

